//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentCampaign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_min_scores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_min_scores()
        {
            this.min_score_spec_link = new HashSet<min_score_spec_link>();
        }
    
        public short ID { get; set; }
        public byte CT_ID { get; set; }
        public byte min_score { get; set; }
        public byte min_score_additional { get; set; }
    
        public virtual CT_enum CT_enum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<min_score_spec_link> min_score_spec_link { get; set; }
    }
}
