//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentCampaign
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrollee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enrollee()
        {
            this.CT_results = new HashSet<CT_results>();
            this.pleas = new HashSet<plea>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public int town_ID { get; set; }
        public string street { get; set; }
        public short house { get; set; }
        public Nullable<short> block { get; set; }
        public Nullable<short> apartment { get; set; }
        public System.DateTime birthdate { get; set; }
        public string passport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_results> CT_results { get; set; }
        public virtual towns_enum towns_enum { get; set; }
        public virtual parent parent { get; set; }
        public virtual writing_locker writing_locker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plea> pleas { get; set; }
    }
}
