//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentCampaign
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnrollmentCampaignEntities : DbContext
    {
        public EnrollmentCampaignEntities()
            : base("name=EnrollmentCampaignEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<countries_enum> countries_enum { get; set; }
        public virtual DbSet<CT_enum> CT_enum { get; set; }
        public virtual DbSet<CT_results> CT_results { get; set; }
        public virtual DbSet<enrollee> enrollees { get; set; }
        public virtual DbSet<faculty_enum> faculty_enum { get; set; }
        public virtual DbSet<parent> parents { get; set; }
        public virtual DbSet<specialty_enum> specialty_enum { get; set; }
        public virtual DbSet<specialty_priorities> specialty_priorities { get; set; }
        public virtual DbSet<towns_enum> towns_enum { get; set; }
        public virtual DbSet<Tree> Trees { get; set; }
        public virtual DbSet<writing_locker> writing_locker { get; set; }
    }
}
