//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentCampaign
{
    using System;
    using System.Collections.Generic;
    
    public partial class speciality_enum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public speciality_enum()
        {
            this.min_score_spec_link = new HashSet<min_score_spec_link>();
            this.speciality_priorities = new HashSet<speciality_priorities>();
        }
    
        public int ID { get; set; }
        public int oksk_ID { get; set; }
        public short group_ID { get; set; }
        public byte financing { get; set; }
        public int university { get; set; }
        public byte form { get; set; }
        public byte training_period { get; set; }
        public byte enroll_in { get; set; }
        public short admission_total { get; set; }
        public short admission_orphans { get; set; }
        public short admission_guards { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    
        public virtual enroll_in_enum enroll_in_enum { get; set; }
        public virtual financing_enum financing_enum { get; set; }
        public virtual form_enum form_enum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<min_score_spec_link> min_score_spec_link { get; set; }
        public virtual oksk_specialities oksk_specialities { get; set; }
        public virtual speciality_group speciality_group { get; set; }
        public virtual training_period_enum training_period_enum { get; set; }
        public virtual university_enum university_enum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<speciality_priorities> speciality_priorities { get; set; }
    }
}
