//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentCampaign
{
    using System;
    using System.Collections.Generic;
    
    public partial class speciality_priorities
    {
        public int plea_ID { get; set; }
        public int speciality_ID { get; set; }
        public byte priority { get; set; }
    
        public virtual plea plea { get; set; }
        public virtual speciality_enum speciality_enum { get; set; }
    }
}
