//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentCampaign
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialty_priorities
    {
        public int enrollee_ID { get; set; }
        public int specialty_ID { get; set; }
        public byte priority { get; set; }
    
        public virtual enrollee enrollee { get; set; }
        public virtual specialty_enum specialty_enum { get; set; }
    }
}
