//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_campaign_ns
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Enrollment_campaign_entities : DbContext
    {
        public Enrollment_campaign_entities()
            : base("name=Enrollment_campaign_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<enrollees> enrollees { get; set; }
        public DbSet<exams_enum> exams_enum { get; set; }
        public DbSet<exams_results> exams_results { get; set; }
    }
}
